server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    ## osspdb: DB? (mysql workbrench?? ?? ??)
    url: jdbc:mysql://localhost:3306/osspdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    ##???? ???? ??
    username: root
    password: park1831
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com:
      dgu:
        wantToGraduate=DEBUG:
#  redis:
#    host: osspcluster.vfxvji.ng.0001.apn2.cache.amazonaws.com
#    port: 6379


##jwt
jwt:
  ##TODO: 테스팅 후 외부 설정으로 돌리기
  secret-key: 6B64DCA4EA2F53EDIKU9AAB215FE7

